---
- name: add repositories
  shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.31/deb/Release.key | gpg --yes --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.31/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list
    wget https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_7.0-2+ubuntu24.04_all.deb -O ~/zabbix-release.deb

- name: install zabbix repositories
  apt:
    deb: ~/zabbix-release.deb

- name: install kubeadm, kubectl and kubelet
  apt:
    name:
    - kubeadm
    - kubelet
    - kubectl
    - containerd
    - zabbix-agent
    state: latest
    update-cache: yes

- name: change routing parameter in sysctl
  shell: |
    sysctl -w net.ipv4.ip_forward=1
    sysctl -p
  
- name: permit initial configuration of kubernetes master node
  shell: |
    kubeadm init
    mkdir ~/.kube
    cp /etc/kubernetes/admin.conf ~/.kube/config && chown $USER:$USER ~/.kube/config
    kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
  become: true
  register: init_result
  failed_when: "'ERROR' in init_result.stderr"

- name: get admin.conf from kube-master
  shell: cat /etc/kubernetes/admin.conf
  register: admin_conf

- name: write to localhost the admin.conf
  copy:
    content: "{{ admin_conf.stdout }}"
    dest: kubectl.conf
    remote_src: true
  delegate_to: localhost
  become: false

- name: clone fluetnd repository
  git: 
    repo: "https://github.com/SF-DP-org/fluentd.git"
    dest: ~/fluentd
    clone: yes

- name: copy zabbix-agent config
  template:
    src: zabbix_agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf

- name: restart zabbix zabbix-agent
  systemd_service:
    name: zabbix-agent
    state: restarted
    ignore_errors: true
